name: generate_sbom
run-name: Generate and publish sBOM to Artifactory

on:
    workflow_call:
    pull_request:
      types:
        - opened
        - synchronize
        - closed
env:
    SBOM_FILENAME: ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha }}.json
    CDXGEN_SPEC_VERSION: 1.4

jobs:
    generate_and_publish_sbom:
        name: Generate sBOM
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout repository
            
            - uses: actions/setup-node@v3
              with:
                node-version: 18

            - uses: actions/setup-java@v3
              name: Setup Java
              with:
                distribution: zulu
                java-version: 17
            
            - uses: actions/setup-python@v4 
              with:
                python-version: 'pypy3.9' 
            
            - name: Install cdxgen
              shell: bash
              run: npm install -g @cyclonedx/cdxgen@9.3.2
            
            - name: Install Poetry
              shell: bash
              run: curl -sSL https://install.python-poetry.org | python3 -
            
            - name: Generate sBOM
              id: generate-sbom
              shell: bash
              run: cdxgen ./ -o ${{ env.SBOM_FILENAME }} --spec-version ${{env.CDXGEN_SPEC_VERSION}}
            
            - uses: actions/upload-artifact@v3
              id: upload-artifact
              continue-on-error: true
              with:
                name: cyclonedx-sbom
                path: ${{ env.SBOM_FILENAME }}
                if-no-files-found: error